services:
  homeassistant:
    ports:
      - "8123:8123"
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    env_file:
      - ./docker/.env
    volumes:
      - ./docker/entrypoint.sh:/init-custom
      - ./docker/config.tar.gz:/tmp/config.tar.gz
      - ../vaillantcloud/src/vaillantcloud:/tmp/vaillantcloud
      - ./custom_components/vaillantcloud/:/tmp/vaillantcloud-component
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/init-custom"]
