set_quick_veto:
  name: Set quick veto
  description: Sets quick veto temperature with optional duration
  target:
    entity:
      integration: mypyllant
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: Quick Veto Temperature
      example: 21
      required: true
      selector:
        number:
          min: 0
          max: 30
          step: 0.1
          mode: slider
    duration_hours:
      name: Duration
      description: Optional duration in hours for the quick veto, default is 3 hours
      example: 3
      selector:
        number:
          min: 0
          step: 0.1
          mode: box

set_manual_mode_setpoint:
  name: Set manual mode setpoint
  description: Sets temperature for manual mode
  target:
    entity:
      integration: mypyllant
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: Manual Mode Setpoint Temperature
      example: 21
      required: true
      selector:
        number:
          min: 0
          max: 30
          step: 0.1
          mode: slider
    setpoint_type:
      name: Type
      description: Manual Mode Type
      example: HEATING
      selector:
        select:
          options:
            - "HEATING"
            - "COOLING"

cancel_quick_veto:
  name: Cancel quick veto
  description: Cancels quick veto temperature and returns to normal schedule / manual setpoint
  target:
    entity:
      integration: mypyllant
      domain: climate

set_holiday:
  name: Set holiday
  description: Set holiday / away mode with start / end or duration
  target:
    entity:
      integration: mypyllant
      domain: climate
  fields:
    start:
      name: Start Date
      description: Optional start date of the holiday, defaults to now
      example: '"2023-01-10 14:00:00"'
      selector:
        datetime:
    end:
      name: End Date
      description: Optional end date of the holiday, defaults to one year in the future
      example: '"2023-01-01 0:00:00"'
      selector:
        datetime:
    duration_hours:
      name: Duration
      description: Optional duration of the holiday in hours, defaults to one year
      example: 72
      selector:
        number:
          min: 1
          mode: box

cancel_holiday:
  name: Cancel Holiday
  description: Cancel holiday / away mode
  target:
    entity:
      integration: mypyllant
      domain: climate

set_zone_time_program:
  name: Set Zone Time Program
  description: Updates the time program for a zone
  target:
    entity:
      integration: mypyllant
      domain: climate
  fields:
    program_type:
      name: Type
      description: Type of the time program (heating, cooling)
      example: heating
      selector:
        select:
          options:
            - "heating"
            - "cooling"
    time_program:
      name: Time Program
      description: A dictionary of days with a list of setpoints, start_time, and end_time (in minutes since midnight)
      example: >
        monday:
            - start_time: 420
              end_time: 1290
              setpoint: 20
        tuesday:
            - start_time: 420
              end_time: 1290
              setpoint: 20
        wednesday:
            - start_time: 420
              end_time: 1290
              setpoint: 20
        thursday:
            - start_time: 420
              end_time: 1290
              setpoint: 20
        friday:
            - start_time: 420
              end_time: 1290
              setpoint: 20
        saturday:
            - start_time: 420
              end_time: 1290
              setpoint: 20
        sunday:
            - start_time: 420
              end_time: 1290
              setpoint: 20

set_dhw_time_program:
  name: Set Water Heater Time Program
  description: Updates the time program for a water heater
  target:
    entity:
      integration: mypyllant
      domain: water_heater
  fields:
    time_program:
      name: Time Program
      description: A dictionary of days with a list of start_time and end_time (in minutes since midnight)
      example: >
        monday:
        - start_time: 330
          end_time: 1260
        tuesday:
        - start_time: 330
          end_time: 1260
        wednesday:
        - start_time: 330
          end_time: 1260
        thursday:
        - start_time: 330
          end_time: 1260
        friday:
        - start_time: 330
          end_time: 1260
        saturday:
        - start_time: 450
          end_time: 1260
        sunday:
        - start_time: 450
          end_time: 1260

set_dhw_circulation_time_program:
  name: Set Water Heater Circulation Time Program
  description: Updates the time program for the circulation pump of a water heater
  target:
    entity:
      integration: mypyllant
      domain: water_heater
  fields:
    time_program:
      name: Time Program
      description: A dictionary of days with a list of start_time and end_time (in minutes since midnight)
      example: >
        monday:
        - start_time: 330
          end_time: 1260
        tuesday:
        - start_time: 330
          end_time: 1260
        wednesday:
        - start_time: 330
          end_time: 1260
        thursday:
        - start_time: 330
          end_time: 1260
        friday:
        - start_time: 330
          end_time: 1260
        saturday:
        - start_time: 450
          end_time: 1260
        sunday:
        - start_time: 450
          end_time: 1260
