#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
VERSION=$(git --git-dir=../myVaillant/.git describe --abbrev=0 --tags)
grep -rl "myVaillant==[0-9]" . --exclude-dir=.venv --exclude-dir=.git | xargs sed -i -E "s/myVaillant==[0-9]+.[0-9]+.[0-9]+b?[0-9]*/myVaillant==${VERSION/v/}/g"