name: Github Pages

on:
  push:
    branches:
      - main
      - mkdocstrings

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t mypyllant-docs . -f docs/Dockerfile
      - run: docker run -v ~/.ssh:/root/.ssh mypyllant-docs gh-deploy --force
