name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        directory: custom_components/vaillantcloud
        filename: vaillantcloud-component.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        files: custom_components/vaillantcloud/vaillantcloud-component.zip
